"""
Exploration of a tetrahedron
via the Python bindings to CGAL generated by SWIG.
The code is based on
https://github.com/CGAL/cgal-swig-bindings/blob/main/examples/python/AABB_polyhedron_facet_intersection_example.py.
"""
from __future__ import print_function
from CGAL.CGAL_Kernel import Point_3
from CGAL.CGAL_Polyhedron_3 import Polyhedron_3

pt1 = Point_3(1.0, 0.0, 0.0)
pt2 = Point_3(0.0, 1.0, 0.0)
pt3 = Point_3(0.0, 0.0, 1.0)
pt0 = Point_3(0.0, 0.0, 0.0)
polyhedron = Polyhedron_3()
P = polyhedron.make_tetrahedron(pt0, pt1, pt2, pt3)

nbv = polyhedron.size_of_vertices()
print('the number of vertices :', nbv)
V = polyhedron.vertices()
for vertex in V:
    print(vertex.point())

nbe = polyhedron.size_of_halfedges()
print('the number of half edges :', nbe)
E = polyhedron.edges()
for e in E:
    print('edge (', e.vertex().point(), end=' , ')
    print(e.next().vertex().point(), end=') ')
    print('has degree', e.vertex_degree())

nbf = polyhedron.size_of_facets()
print('the number of facets :', nbf)
F = polyhedron.facets()
for f in F:
    print('facet is triangle?', f.is_triangle(), end=',')
    print(' with degree', f.facet_degree())

cnt = 0
for facet in F:
    print('facet', cnt, ':')
    e = facet.halfedge()
    print(e.vertex().point())
    print(e.next().vertex().point())
    print(e.next().next().vertex().point())
    cnt = cnt + 1
